.gitignore, cli.js, package-lock.json, package.json
Closes #1
Just sets up the entry point, that's all for now.
=> Establish CLI

cli.js, package-lock.json, package.json, test/index.js
=> Adopt Express

.prettierignore, cli.js, package-lock.json, package.json
=> Adopt ShareDB

cli.js, test/index.html
=> List files

package-lock.json, package.json, src/App.jsx, src/CodeEditor.jsx
used the codemirror-ot package to allow instant updates to code in editor
=> Live updates

cli.js, package-lock.json, package.json, src/App.jsx, test/TestFile2.txt, test/app.jsx, test/index.html
This version works when you dont remove anything from the file, on enter it will save the line but if you try and remove a whole line or more it adds some objects instead
=> No backspace auto save

README.md, src/App.jsx, src/CodeEditor.jsx, src/main.jsx, src/style.css
* Closes #48
* Remove unused CSS found via Chrome DevTools coverage profiling
=> CSS Cleanup

src/App.jsx, src/settings.jsx, src/style.css
Hey take a look at the new scroll bar and let me know what you think. I'm not totally sure about the design so please make changes if you want
=> new scroll bar

src/client/App.jsx, src/client/Sidebar/File.jsx
=> Fix file deleting

src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/widgets.ts, test/sampleDirectories/kitchenSink/script.ts
=> Unlock interactive widgets

src/client/App.tsx, src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/index.tsx, src/client/CodeEditor/widgets.ts, src/server/computeInitialDocument.js, src/server/index.js, test/sampleDirectories/kitchenSink/script.ts
=> Frequent Auto-Save during Widget Interactions

package-lock.json, package.json, test/listFiles.test.js
=> Upgrade deps and fix tests

package.json, src/client/App.tsx, src/client/Resizer/index.tsx, src/client/Resizer/styles.scss, src/client/Settings.tsx, src/client/Sidebar/index.tsx, src/client/Sidebar/styles.scss, src/client/SplitPaneResizeContext.tsx, src/client/style.scss, test/sampleDirectories/kitchenSink/index.html, test/sampleDirectories/kitchenSink/test.ts
=> Split Pane Resizer

src/client/SplitPaneResizeContext.tsx
These changes make it not crash under SSR.
=> Support SSR

README.md
=> Usage Docs

src/client/Sidebar/FileListing.tsx
Closes #192 
With some help from @EvWhymark  I was able to make a basic confirmation window when deleting a file. Very basic right now but could work on it to make it nicer.
=> WIP: Delete File Confirmation

README.md, src/client/App.tsx, src/client/Sidebar/ConfirmationBox.jsx, src/client/Sidebar/DirectoryListing.tsx, src/client/Sidebar/FileListing.tsx, src/client/Sidebar/Item.jsx, src/client/Sidebar/Item.tsx, src/client/Sidebar/Listing.tsx, src/client/Sidebar/index.tsx, src/server/index.js, test/sampleDirectories/kitchenSink/cool.css
Closes #150 
Todo: Fix issue where clicking rename directory button while that directory is not currently being renamed toggles the directory open/close.
=> Inline File Renaming

src/client/Settings.tsx, src/client/Sidebar/ConfirmationBox.tsx, src/client/bootstrap.ts
=> Refactor Bootstrap imports

src/client/Sidebar/FileListing.tsx, tsconfig.json
=> Squash TypeScript Warnings #212

src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/widgets.ts, test/sampleDirectories/kitchenSink/hexContinousTest1.js, test/sampleDirectories/kitchenSink/widgetTest1.js
This pull request contains changes from the previous two pull requests (hex colors and hex colors auto-update).
=> Widgets: show colors in the code

src/client/TabList/style.scss
Changed scroll bar to only appear when tab list overflows the width of the editor window.
=> Update Scrollbar Behavior

src/client/App.tsx, src/client/reducer.ts
Currently correctly refactored the code so setTabList is now used properly within a reducer.
=> Refactor setTabList to useReducer

src/client/App.tsx, src/client/reducer.ts
#237 
Changes the entirety of useTabState over to our reducer function. I did not delete useTabState.ts however I believe that we can go ahead and remove/archive it if the logic in the reducer function looks good.
=> Refactor useTabState to useReducer

src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/widgets.ts
User holds alt key to activate the feature.
Note: There is potentially noticeable delay (~2 seconds on a 385 line file with a few places that can use interactive widgets) between pressing the alt key and seeing the highlights. The code I have written checks a regex containing all relevant regexes against every line. The number of checks is likely inevitable. The time it takes to run might not be.
=> Highlight interactive widgets

src/client/App.tsx, src/client/reducer.ts, src/client/useActions.ts, src/client/useFileCRUD.ts, src/server/index.js
Following https://github.com/vizhub-core/vzcode/pull/246 and https://github.com/vizhub-core/vzcode/commit/b90cdc29bb1c2576dfa37f00893f17c3dafea0f4 (accidentally pushed to main 🤦), this PR contains further refactorings that split up App.tsx substantially and add more rigorous types.
Also fixed a server bug where file renaming was broken.
=> Split up App.tsx substantially

src/server/index.js
=> Make Port Configurable

index.html, package-lock.json, package.json, src/client/App.tsx, src/client/TabList/Tab.tsx, src/client/TabList/style.scss, src/client/VZSidebar/FileListing.tsx, src/client/VZSidebar/Item.tsx, src/client/VZSidebar/Listing.tsx, src/client/VZSidebar/index.tsx, src/client/VZSidebar/styles.scss, src/client/bootstrap.ts, src/client/style.scss, test/sampleDirectories/kitchenSink/index.html
A holistic pass through the styles of the entire application.
New feature: Highlight the active file in the sidebar!
=> UI Style Pass

src/client/App.tsx, src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/index.tsx, src/client/CodeEditor/json1PresenceBroadcast.ts, src/client/PresenceNotifications/PresenceNotifications.test.ts, src/client/PresenceNotifications/index.tsx, src/client/VZSettings.tsx, src/client/useActions.ts, src/client/usernameLocalStorage.ts, src/client/vzReducer/index.ts, src/client/vzReducer/setUsernameReducer.ts, src/types.ts
* Refactor how username is passed into presence generation logic, using a ref
* Split out local storage logic into a separate module
* Overhaul `PresenceNotifications` implementation and add tests for its parts
=> Refactor and clean up presence notifications

src/client/VZSidebar/index.tsx, src/client/VZSidebar/styles.scss
Closes #280 
Closes #279 
* #280 
* #279
=> Add empty state for sidebar

src/server/handleAIAssist.js, src/server/index.js, test/sampleDirectories/kitchenSink/script.ts
Closes #286
1. **Objective**: The changes aim to handle AI errors and refactoring of code.
2. **Affected Files**: Three files have been modified.
* `handleAIAssist.js` - Added (55 additions & 0 deletions)
* `index.js` - Refactored (8 additions & 42 deletions)
* `script.ts` - Updated (2 additions & 0 deletions)
**Detailed Changes:**
1. **`handleAIAssist.js`**:
- A new module was added which imports the OpenAI library and defines a function `handleAIAssist`.
- The function is responsible for generating asynchronous AI responses and mutating the ShareDB document.
- In case of any errors, it sends a `500 Internal Server Error` message.
2. **`index.js`**:
- Refactoring involved extracting the AI Assist logic and moving it to the newly created `handleAIAssist.js` module.
- Removed the direct …
=> Handle AI errors, refactor

package-lock.json, package.json, src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeErrorOverlay/index.tsx, src/client/CodeErrorOverlay/style.scss, test/sampleDirectories/kitchenSink/package.json
=> Iterate error styling, fix JSX highlighting

src/client/CodeEditor/json1PresenceDisplay.ts
Goal: Fix issue where a multiple line selection causes a cursor to appear at the end of each line
Closes #206
=> Fix Cursor Bug

src/client/CodeEditor/typeScriptCompletions.ts, src/client/useTypeScript/requestTypes.ts, src/client/useTypeScript/worker.ts, test/sampleDirectories/kitchenSink/test.ts
=> Pass latest content for completions

src/client/TabList/index.tsx, src/client/VZSidebar/CreateFileModal.tsx, src/client/VZSidebar/index.tsx, src/client/useFileCRUD.ts
Prompt the user with a modal when they attempt to create a new file.  When used with the createfile shortcut (alt-n) it creates a new file named "UnnamedFile".  In future versions users will be prompted with the same Modal when creating a file with the shortcut.
=> File renaming modal

src/client/AIAssistWidget/index.tsx, src/client/AIAssistWidget/style.scss, src/client/App.tsx
=> Add icon for AI Assist

src/client/CodeErrorOverlay/index.tsx
=> Error Overlay should Clear on Escape Key

src/client/VZSidebar/DeleteConfirmationModal.tsx
Updates DeleteConfirmationModal.tsx
=> 269 Delete UX: "Enter" should submit form

src/client/App.tsx, src/client/TabList/index.tsx, src/client/VZSidebar/CreateFileModal.tsx, src/client/VZSidebar/index.tsx
Users are now prompted with the new file creation modal when they use the create file keyboard shortcut. 
Fixed small bug where previous filename would be in the new name field of subsequent modals.
=> Better file renaming v2

src/client/VZSidebar/CreateFileModal.tsx
Added functionality to check if a filename is valid before allowing users to proceed with the create file button.
=> Validate Filename changes

src/client/useTypeScript/worker.ts
=> Refine TS linting

src/client/useTypeScript/worker.ts
Closes #354 
Just was initializing the tsErrors incorrectly.  Quick one line fix.
=> Don't crash on non-JS or TS files

src/server/handleAIAssist.js, test/sampleDirectories/kitchenSink/scatterPlot.js
In the parent project, `npm run dev` was not happy with the way this import was phrased. Something about ES modules not being provided... This should make that work.
=> Fix AI Assist import error

package-lock.json, package.json, src/client/VZSidebar/DeleteConfirmationModal.tsx, src/client/VZSidebar/Item.tsx
=> Fix delete confirm modal

src/types.ts
=> Iterate Types

package-lock.json, package.json, src/client/CodeEditor/getOrCreateEditor.ts
=> Adopt codemirror-indentation-markers

package-lock.json, package.json, src/client/CodeEditor/getOrCreateEditor.ts
=> Adopt codemirror-minimap

package-lock.json, package.json, src/client/CodeEditor/getOrCreateEditor.ts
=> Adopt VSCode keybindings

package-lock.json, package.json, src/client/App/style.scss, src/client/TabList/style.scss, src/client/VZSidebar/styles.scss, test/sampleDirectories/kitchenSink/longFile.ts
=> Upgrade dependencies, iterate styles

package.json
Included my name and github url to the contributors list
=> Add to Contributor

package-lock.json, package.json, src/server/computeInitialDocument.js, test/listFiles.test.js, test/sampleDirectories/listFilesIgnore/.ignore, test/sampleDirectories/listFilesIgnore/subdirectory/.ignore, test/sampleDirectories/listFilesIgnoreEscape/!/.ignore, test/sampleDirectories/listFilesIgnoreEscape/#/.ignore, test/sampleDirectories/listFilesIgnoreEscape/**/.ignore, test/sampleDirectories/listFilesIgnoreEscape/*/.ignore, test/sampleDirectories/listFilesIgnoreEscape/.ignore, test/sampleDirectories/listFilesIgnoreEscape/?/.ignore, test/sampleDirectories/listFilesIgnoreEscape/[/.ignore, test/sampleDirectories/listFilesIgnoreEscape/\/.ignore, test/sampleDirectories/listFilesIgnoreEscape/]/.ignore
don't include ignored file in the file tree, according to the contents of .gitignore and .ignore files
inspired by [ripgrep](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#automatic-filtering) I set up vzcode to skip th files that match the patterns in the .gitignore or .ignore files it encounters when building the file tree. 
Differently from git or ripgrep, I'm not searching parent directoriees for ignore files and only take into account ignore files in the current working directory or it's descendants.
The implementation of the ignore pattern matching is based on [globby](https://github.com/sindresorhus/globby/blob/bd76374396886157357883b2223a342ff983b032/ignore.js#L28), with a few improvements. 
- when a (git)ignore file is found in a directory whose relative path includes …
=> #110 respect .gitignore

package-lock.json, package.json, src/client/CodeEditor/getOrCreateEditor.ts
Removing this extension as it was causing performance problems.
Related: https://github.com/replit/codemirror-minimap/issues/36
=> Un-adopt CodeMirror Minimap for performance

src/client/AIAssist/AIAssistWidget/index.tsx, src/client/VZMiddle.tsx, src/client/bootstrap.ts, src/server/generateAIResponse.js
Allows external overrides for tooltip text and click handler.
=> Customize AI assist options

src/client/CodeEditor/typeScriptCompletions.ts
=> Disable autocomplete after certain characters

README.md, package-lock.json, package.json
The Win32 thing we added actually ended up breaking the build on Linux.
As a workaround, I've added instructions in the README for Windows users.
=> Upgrade deps, make it work on Linux again

src/client/CodeEditor/typeScriptLinter.ts, src/client/useTypeScript/worker.ts, test/sampleDirectories/kitchenSink/index.js
=> Fix TS lib

src/client/AIAssist/AIAssistWidget/style.scss, src/client/TabList/style.scss, src/client/VZSidebar/styles.scss
Ready for review.
New colors for the sidebar were replaced with the old colors
=> Closes #466

src/client/VZSidebar/styles.scss
=> changed background color of active file

src/client/VZSidebar/index.tsx, src/client/VZSidebar/styles.scss
=> started #456

.gitignore, src/client/VZSidebar/styles.scss
I added a maximum height for the class of file-or-directory.
=> Stable layout

src/client/App/style.scss, src/client/Icons/CloseSVG.tsx, src/client/Icons/EditSVG.tsx, src/client/Icons/GearSVG.tsx, src/client/Icons/NewSVG.tsx, src/client/Icons/TrashSVG.tsx, src/client/Icons/index.tsx, src/client/VZSidebar/Item.tsx, src/client/VZSidebar/index.tsx, src/client/VZSidebar/styles.scss
Added new icon for create file
=> Start on new designs for header

src/client/VZSidebar/index.tsx
=> Add new settings icon

src/client/useURLSync.ts
=> First pass fix of back button

src/client/VZSidebar/styles.scss, src/client/index.ts
=> Export icons

src/index.ts
Iterate how exports are done, so we catch the icons.
=> Iterate top level exports

src/client/CodeErrorOverlay/index.tsx, src/client/CodeErrorOverlay/style.scss
=> Handle errors present on page load, iterate styles

src/client/AIAssist/AIAssistWidget/index.tsx, src/client/AIAssist/AIAssistWidget/style.scss, src/client/AIAssist/Spinner.jsx
Worked with demhos && NghiaMinhHuynh!
Added the implementation of the Spinner in a new file called Spinner.jsx.
Added the Spinner's CSS into the styles.scss.
Changed the return of the index.tsx react component. Made it so that it will render either the AI assist icon or the spinning. If the API id is not NULL it will show the spinner, else it will show the ai assist icon.
=> Ai assist spinner

src/client/usePrettier/worker.ts, test/sampleDirectories/kitchenSink/App.svelte
=> Temporarily disable Svelte Prettier error

src/client/VZCodeContext.tsx, src/client/useActions.ts, src/client/useKeyboardShortcuts.ts, src/client/vzReducer/index.ts, src/client/vzReducer/setActiveFileLeftRightReducer.ts
Added new file setActiveFileLeftRightReducer.ts to handle switching tabs.
Added it to the reducer and actions.
Have it called in useKeyboardShortcuts.ts
Closes #442
=> Added Support for Page-Up, Page-Down Keybinds

src/client/VZLeft.tsx, src/client/VZSettings.tsx, src/client/VZSidebar/index.tsx
A bit of progress on leveraging Context to reduce prop drilling.
=> Progress on context refactoring

src/client/useTypeScript/worker.ts
=> Handle race conditions for TS file system init

package.json, src/client/usePrettier/prettier-plugin-svelte-browser.js, src/client/usePrettier/worker.ts, test/sampleDirectories/kitchenSink/App2.svelte, test/sampleDirectories/kitchenSink/App3.svelte
Until the upstream package is published here
https://www.npmjs.com/package/prettier-plugin-svelte
we inline the browser build from
https://github.com/sveltejs/prettier-plugin-svelte/pull/430
=> Support Prettier for Svelte

package-lock.json, package.json, src/client/CodeEditor/style.scss
Worked with hosand
I applied the CSS but removed the padding because it creates a random box. However, I'm confused about what you mean by the palette's color. So I tried to match the color with the VZSidebar.
=> Intelligent Autocompletions: Styling v1

src/client/useTypeScript/worker.ts, tsconfig.json
Added, "noImplicitAny": false to tsconfig.json
=> anytype warning

src/client/useTypeScript/worker.ts, test/sampleDirectories/kitchenSink/index.js
=> Ignore TS warning

src/client/AIAssist/AIAssistWidget/index.tsx, src/client/AIAssist/AIAssistWidget/style.scss, src/client/AIAssist/index.ts, src/client/CodeEditor/index.tsx, src/client/Icons/PlaySVG.tsx, src/client/Icons/index.tsx, src/client/RunCodeWidget/index.tsx, src/client/RunCodeWidget/style.scss, src/client/TabList/style.scss, src/client/VZCodeContext.tsx, src/client/VZMiddle.tsx, src/client/shouldTriggerRun.ts, src/client/useKeyboardShortcuts.ts, src/client/usePrettier/index.ts, src/client/useRunCode.tsx, src/server/computeInitialDocument.js, src/server/index.js, src/types.ts
=> Manual Run

src/client/useTypeScript/worker.ts, test/sampleDirectories/kitchenSink/index.js
=> Disable TS linting error on property does not exist

src/client/useTypeScript/worker.ts, test/sampleDirectories/kitchenSink/react.js, test/sampleDirectories/kitchenSink/test.js
=> Refine linting

src/client/VZSidebar/Item.tsx, src/client/VZSidebar/styles.scss
I update the styles.scss file in the rename-input classname for better styling. I also add the FileSVG logo when we click to rename it keep the icon on the left while renaming.
=> Better-Styling-for-Rename

src/client/CodeEditor/codemirror-interact.ts, src/client/CodeEditor/widgets.ts, src/server/generateAIResponse.js, test/sampleDirectories/kitchenSink/colorPickerSyncTest.js
Got it! Solved in https://github.com/vizhub-core/vzcode/pull/583
Before: 
https://github.com/replit/codemirror-interact/assets/68416/4a842178-8b77-46a7-bcf3-ff0c0c0ad6d6
After:
https://github.com/replit/codemirror-interact/assets/68416/39900a95-fd05-4b30-9f77-6a27c62399d1
=> Fix color picker collab crash

src/client/VZSidebar/index.tsx, src/client/VZSidebar/styles.scss, src/client/VZSidebar/useDragAndDrop.tsx
I made the DragAndDrop.jsx into a custom hook that returns just the necessary functions and components. 
I added the custom hook to the index. jsx for the VZSidebar.
I edited the CSS slightly so that it's a solid border instead of dashed. In my opinion, it looks better.
=> drag and drop with entire sidebar

src/client/useTypeScript/worker.ts
added the error code to ignore ts warning
=> ts warning for iterated

src/client/useTypeScript/worker.ts, test/sampleDirectories/kitchenSink/reactTest.jsx
=> Support jsx react

src/client/useFileCRUD.ts
Small change to make sure it only deletes the exact directory named
Closes #600
=> Fixes Issue #600, Bug with Directory Deletion

src/client/VZSidebar/index.tsx, src/client/VZSidebar/styles.scss
I wanted to get rid of that intermediate div with the border, which was causing the UI to feel a bit off. I also wanted to make the drop interaction more explicit, so I changed it to actually show this instead of just having a green border.
=> Simplify drop zone for files

src/client/CodeEditor/widgets.ts, test/sampleDirectories/kitchenSink/index.js, test/sampleDirectories/kitchenSink/styles.css
=> Get color picker working in CSS

src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/index.tsx, src/client/CodeEditor/typeScriptLinter.ts, src/client/VZMiddle.tsx, src/client/useTypeScript/requestTypes.ts, src/client/useTypeScript/worker.ts, test/sampleDirectories/kitchenSink/index.js
=> Add option to disable global linting error

src/client/AIAssist/AIAssistWidget/index.tsx
=> Delay in AI

package.json, src/client/VZSidebar/CreateFileModal.tsx
=> Adds Validation to File Creation Keyboard Shortcut

src/client/useURLSync.ts
=> Ensure the correct file is open on page load from URL

src/client/CodeEditor/widgets.ts, test/sampleDirectories/kitchenSink/index.js, test/sampleDirectories/kitchenSink/react.js, test/sampleDirectories/kitchenSink/script.ts, test/sampleDirectories/kitchenSink/typicalFiles/index.js
https://github.com/vizhub-core/vzcode/pull/new/issue586%232
=> added checkbox widget

src/client/VZSettings.tsx
I made it so the font and font size will remain after reloading the tab
=> Persist Font

src/client/VZCodeContext.tsx, src/client/VZLeft.tsx, src/client/VZSidebar/CreateDirModal.tsx, src/client/VZSidebar/CreateFileModal.tsx, src/client/VZSidebar/index.tsx, src/client/useFileCRUD.ts, src/server/index.js
Closes #104 
Just uses the file svg for now to be able to differentiate it from file creation, should likely have it's own svg at some point.
=> Adds ability to create directories in VZCode

src/client/VZSettings.tsx
=> Fix SSR case for localstorage

src/client/VZSidebar/CreateDirModal.tsx, src/client/VZSidebar/CreateFileModal.tsx
=> Duplicate Filename Prevention on File Creation

src/client/RunCodeWidget/index.tsx, src/client/RunCodeWidget/style.scss
Made it so that the run icon spins when it is pressed
=> Tell if run icon is pressed

package.json
=> Contribution-Nghia

package.json, src/client/VZSettings.tsx
https://github.com/vizhub-core/vzcode/pull/new/issue356
=> Submit Settings Enter key

package-lock.json, package.json
=> Add optional Rollup Windows dependency

package-lock.json, package.json
=> Add optional mac dependency

src/client/CodeEditor/json1PresenceDisplay.ts
Set color hash lightness to 0.75.
Take a look at it and let me know if the lightness value needs to be adjusted. In the limited testing I preformed the colors looked good to me.
=> Set color hash lightness to 0.75

src/client/VZCodeContext.tsx, src/client/VZSidebar/Item.tsx, src/client/VZSidebar/index.tsx, src/client/VZSidebar/styles.scss, src/client/useKeyboardShortcuts.ts
Ctrl-0 should focus on sidebar
added sidebarRef to context, created keyboard command for ctrl-0, imported to sidebar index.
=> Shortcut to focus on sidebar

src/client/useTypeScript/worker/constants.ts, test/sampleDirectories/kitchenSink/TSerrortest.ts
Turns out the specific error code for this one was 18046 not 2571 for type unknown. I reopened it in a different branch because the old one was something like 56 commits behind
Changed TSErrortest to reflect new test
=> 655 ignore ts lint about unknown reopen

test/sampleDirectories/kitchenSink/testing.js
=> Created testing.js to fix the unknown issue

src/client/themes/vizhubTheme/index.ts
Changed colors of vizhub to pastel theme might need to lighten the colors more.
=> changed colors of vizhub to pastel

src/client/CodeEditor/json1PresenceDisplay.ts
Please let me know if this works, I did some testing in a long javascript file, but I havent tested it anywhere else. As far as I know, it should work without many issues.
=> Follow user draft, users' scrolls follow the other's cursor around the same file. Works for clicking and arrow-key movement.

src/client/CodeEditor/index.tsx, src/client/VZCodeContext.tsx, src/client/useKeyboardShortcuts.ts
Ctrl-0 to Alt-1 and Alt-2 for code editor focus
=> Code editor focus

src/client/TabList/style.scss, src/client/VZSidebar/styles.scss
=> Minor layout improvements

src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/index.tsx, src/client/CodeEditor/json1PresenceDisplay.ts, src/client/VZCodeContext.tsx, src/client/VZSidebar/index.tsx, src/client/VZSidebar/styles.scss, src/client/useActions.ts, src/client/vzReducer/index.ts, src/client/vzReducer/toggleAutoFollowReducer.ts
Closes #768
Also adds color to pin icon! Green when auto-follow is enabled.
=> Refactor auto-follow state & add color to pin icon

src/client/useKeyboardShortcuts.ts, src/client/vzReducer/createInitialState.ts
=> Don't crash if no active file

src/client/CodeEditor/getOrCreateEditor.ts, test/sampleDirectories/kitchenSink/index.html, test/sampleDirectories/kitchenSink/index.js
=> HTML Autocomplete

src/client/VZSidebar/index.tsx
=> Format tooltip text nicely for keyboard shortcuts

src/client/VZCodeContext.tsx, src/client/VZSidebar/DirectoryListing.tsx, src/client/VZSidebar/FileListing.tsx, src/client/VZSidebar/Listing.tsx, src/client/VZSidebar/index.tsx, src/client/VZSidebar/styles.scss, src/client/useActions.ts, src/client/vzReducer/createInitialState.ts, src/client/vzReducer/index.ts, src/client/vzReducer/updatePresenceIndicatorReducer.ts, src/types.ts
=> Start on presence in sidebar

src/client/CodeEditor/index.tsx, src/client/RunCodeWidget/index.tsx, src/client/TabList/index.tsx, src/client/VZCodeContext.tsx, src/client/VZMiddle.tsx
=> Progress towards split pane

.env.example, src/server/generateAIResponse.js, src/server/setupEnv.js, test/sampleDirectories/kitchenSink/App.svelte, test/sampleDirectories/kitchenSink/fft.js, test/sampleDirectories/kitchenSink/index.html, test/sampleDirectories/kitchenSink/index.js
Closes #850
Instructions for use:
* Set up LMStudio on a machine in your network
* Configure it to expose to local network
* Change port to 8080 (for some reason the default didn't seem to work)
* Set VZCODE_AI_BASE_URL to your local API endpoint (see `.env.example`)
=> Support local AI server

src/client/VZSidebar/styles.scss
Changed the hex color value within the VZSidebar style.scss to make the username initial stand out more.
=> Fixed the color for presence in sidebar

package-lock.json, package.json, src/client/CodeEditor/Copilot/index.ts, src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/index.tsx, src/client/VZMiddle.tsx, src/server/handleAICopilot.js, src/server/index.js, vite.config.js
=> First pass copilot-like AI

src/client/VZSettings.tsx
https://github.com/vizhub-core/vzcode/issues/825
Added the font sizes requested: 10px, 12px, 14px
=> More font size options

src/client/CodeEditor/InteractiveWidgets/colorsInTextPlugin.ts, src/client/CodeEditor/style.scss, src/client/VZKeyboardShortcutsDoc.tsx
- Updates buttons look for shortcut menu
- Implemented shortcut tooltip pop-up when hovering over color circle
=> 799 icons for keyboard shortcuts

src/server/generateAIResponse.js
I'm going to pr this for now, my implementation for claude was going to include this but that seems more indepth and would take more time. So I would rather have this pushed instead of waiting on those changes.
=> Update to 4o

src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/rainbowBrackets.ts, src/client/VZSettings.tsx
https://github.com/vizhub-core/vzcode/issues/722
Working on this right now, created a button so far to toggle.
=> Rainbow bracket toggle button

package-lock.json, src/client/CodeEditor/InteractiveWidgets/colorPicker.ts
When users press alt + left click on the color circle they will now have the color picker appear near their mouse instead of having the color picker remain in the top left of their screen. Users can click outside of the color picker to close the color picker.
=> 189 color pick position edited

src/client/VZSettings.tsx
https://github.com/vizhub-core/vzcode/issues/675
=> Theme persist

src/client/RunCodeWidget/index.tsx
https://github.com/vizhub-core/vzcode/issues/635
Run button spins when you "run the code" by pressing Ctrl+S or Shift+Enter
=> Run button spins on keybinds

src/client/themes/themes.ts, src/client/themes/uiwImports.ts, src/client/themes/vizhubTheme/index.ts
Related to 
* https://github.com/uiwjs/react-codemirror/issues/710
=> Attempt to Fix UIW Imports

src/client/App/index.tsx, src/client/CodeEditor/Copilot/index.ts, src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/index.tsx, src/client/VZMiddle.tsx, src/server/handleAICopilot.js, src/server/index.js
This set of changes makes the AI "Ghost Text" Copilot-like feature work pretty well.
=> Fix AI Completions

package-lock.json, package.json, src/client/App/index.tsx, src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/index.tsx, src/client/VZMiddle.tsx, src/client/useESLint/index.ts, src/client/useESLint/worker.ts, src/server/featureFlags.js
Introduce ESLint support with asynchronous linting capabilities, enabling `.jsx` and `.js` linting.
=> Integrate ESLint for enhanced code linting

src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/index.tsx, src/client/useESLint/worker.ts
Supports SSR, fast-follow as an improvement on the changes in:
* https://github.com/vizhub-core/vzcode/pull/918
=> Lazily instantiate the Web work on client-side only

src/client/useESLint/worker.ts
=> Add enableJSXLinting feature flag, disable for now

src/client/VZSidebar/VisualEditor.tsx, test/sampleDirectories/visualEditor/config.json
=> Visual editor cleanup

package-lock.json, package.json, src/client/VZSidebar/AIChat/Message.tsx, src/server/aiChatHandler/chatOperations.ts, src/server/index.ts
Should give us image support from upstream runtime
=> Upgrade deps
