vizhub-core/vzcode

cli.js, src/App.jsx, src/CodeEditor.jsx, src/getOrCreateEditor.js, src/json1PresenceBroadcast.js, src/json1PresenceDisplay.js, src/randomId.js, test/index.html
Closes #16
First pass of the feature only.
Summary of changes:
* Set up ShareDB `LocalPresence` instance
* Listen for changes in CodeMirror
* Broadcast presence using ShareDB API
* Display the remote presence
* Tested multiple connections (had to pass the `sort` arg to `Decoration.set` to fix this)
* Tested editing after receiving presence. Had to add a `setTimeout` before dispatching the change to fix this, so there are not synchronous nested CodeMirror updates. This feels like somewhat of a hack, but not sure a better way.
* Tested that presence cursors are transformed correctly when editing
* Tested that presence cursors work across newlines
Current limitations:
* Everyone's cursor is yellow
* Does not handle removing presence yet
* Does not yet support range selections (only the start …
=> Presence First Pass

package.json
This change makes it so that any tooling around Prettier will use the same configuration.
This will avoid future accidental formatting changes in PRs, such as [this change to App.js](https://github.com/vizhub-core/vzcode/pull/85/files/ec2c2c3731a491191164cbcf96859126eacd7d0f#diff-d274a54187c91ba0f532df2a9e194e27ab50e988f5e4c33f5a7893918320c661).
Specifically, this change makes the VSCode Prettier plugin do the same thing as our `npm run prettier` script, so no matter how we invoke Prettier the results should be the same.
=> Adopt .prettierrc

src/client/CodeEditor/widgets.ts, test/sampleDirectories/kitchenSink/widgetTest1.js
This allows the user to move their mouse around rotate(x) to change the value of x. This can be used to rotate SVGs (D3). This commit also contains the color picker and vec2 widgets commit. We did not discuss this feature in the meeting, but I thought it was worth exploring after I finished the previous commit.
=> Add rotate interactive widget

src/client/App.tsx, src/client/Sidebar/ConfirmationBox.jsx, src/client/Sidebar/DirectoryListing.tsx, src/client/Sidebar/FileListing.tsx, src/client/Sidebar/Item.jsx, src/client/Sidebar/Item.tsx, src/client/Sidebar/Listing.tsx, src/client/Sidebar/index.tsx
Implemented the modal confirmation box as was requested in #199 . 
I added a couple of new functions in Item.jsx to handle opening and closing the modal. 
“handleDeleteFileClick” no longer accepts event as an argument as it is no longer called as a result of a button click.
Files referencing "handleDeleteFileClick" were updated to reflect this change. 
Still new to all of this. Please let me know if there is anything that could be improved on or anything I missed. :)
=> WIP Delete Confirmation Modal

src/client/TabList/style.scss
Added a very simple, and possibly temporary, fix to the tablist going off screen. When the length of the tab list exceeds the width of the editor a scroll bar appears.
=> 172 usability improvements tab list goes offscreen

src/client/CodeEditor/widgets.ts, test/sampleDirectories/kitchenSink/hexContinousTest1.js, test/sampleDirectories/kitchenSink/widgetTest1.js
This pull request includes the commit that adds the hex color picker interactive widget.
So far, this pull request makes it so hex colors update in the code automatically as the user uses the color picker.
However, implementing this feature for colors in the format rgb(123, 4, 28) would require creating our own version of codemirror-interact. The existing version uses the following steps:
1. Find the section of code the user wants to edit using regex and the mouse's location.
2. Give the onClick function a function that sets the text for the section previously found
3. My code then calls the setText function whenever the user changes the color in the color picker.
These steps (particularly the first two) do not allow the section of code to change. This breaks the feature because rgb( , , …
=> Widgets make color picker live updating

package-lock.json, package.json, src/client/App.tsx, src/client/CodeEditor/getOrCreateEditor.ts, src/client/Settings.tsx, src/client/Sidebar/DirectoryListing.tsx, src/client/Sidebar/FileListing.tsx
Removes `react-select` as a dependency, as it's a heavyweight package, and it's causing some downstream dependency hell issues.
=> Un-adopt react-select, upgrade dependencies

src/client/App.tsx, src/client/Sidebar/Item.tsx, src/client/useTabsState.ts
Closes #223 
Closes #215 
Decided to bundle the fix to both these bug fixes together since they relate to similar issues. However the solutions to the problems are not related.
The first solution for #223 is related to a pitfall of react's useState. useState as stated in the documentation "does not change the current state in already executing code".  So by calling closeTab multiple times like we used to, resulted in the tabList not being updated at all because of all the conflicting setTabList calls. To solve this issue I created a new method that takes in array of fileIds that we want to close and only uses one setTabList call.
While tackling this issue it made me realize an interesting drawback from using reacts useStates. #223 was difficult to debug and it took a lot of time to …
=> Delete directory/files bug fixes

src/client/SplitPaneResizeContext.tsx
There was an error when you load the page for the first time, before the split pane size is stored in local storage.
This fix initializes the context to solve the error.
=> Fix split pane error

src/client/CodeEditor/style.scss, src/client/PrettierErrorOverlay/style.scss, src/client/style.scss, test/sampleDirectories/kitchenSink/index.js
Before:
After:
Closes #259 
Also caught some styling issues with the font in the editor itself.
=> Iterate styles of prettier error overlay

src/client/usePrettier/index.ts
Closes #157 
Added the functionality to stop prettier from running on cursor move and keydown events. Still does not properly handle when others are changing text and waiting on the AI generation. I generally added a keydown event so if a user wants to have prettier run they will need to leave the editor idle (no keyboard inputs or mouse inputs). We can easily change it so it only does it on specific arrow keys if we want.
=> Debounce Prettier on cursor and keyboard events

src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/typeScriptLinter.ts, src/client/useTypeScript/requestTypes.ts, src/client/useTypeScript/worker.ts
Builds upon #305 and uses our typescript server to now provide linting into our code editor. Utilizes typescript to give more errors that our prettier errors might have missed.  Currently the feature flag for this is set to off and should remain so until we resolve an issue that came up with my implementation.  When inside the editor if a user were to drag and select text and then delete said text it results in the shareDB getting out of sync with the local editor. See attached error:
I currently have no ideas to why this might be happening.  The feature flag should not be turned on until this issue is resolved.
=> TypeScript Linter

src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/typeScriptLinter.ts, src/client/useTypeScript/requestTypes.ts, src/client/useTypeScript/worker.ts
Closes #336 
Thanks @curran, your suggestion worked! This gets rid of all the bugs that I found with my testing in the typescript linter. The content that the typescript server was running off of in the linter was out of date and we just needed to update the content with the shareDBDoc. I have also turned the feature flag for the linter on so it will be running in the codebase.
=> TypeScript linter bug fix

src/client/CodeEditor/typeScriptCompletions.ts
Closes #370 
Added some basic conditional logic to prevent the autocompletions from appearing after specific characters (single and double quotes, parentheses, semicolons). Can add onto the conditional if the issue persists on other character types.
=> Prevent Unnecessary Completions

src/client/useTypeScript/worker.ts
Current code changes works to fix issues relating to deleting all file content.  Still have issues relating to initially having no file content.  Most likely related to how we are handling our initial render and how the typescript VFS handles empty string file contents.
WIP:
On initial render the file system does not properly update with a blank file.
Steps to replicate:
- Launch local server
- Have a blank (no file content) .ts or .js file and open it
-  Attempt to update file
In the following screenshot script.ts was originally blank and I tried to edit the file.
=> WIP Improper Typescript filesystem update

src/client/CodeEditor/typeScriptCompletions.ts
Closes #362 
Autocomplete now forcefully moves the cursor to the correct position after doing a completion.
=> Fix Autocomplete Cursor Bug

src/client/useTypeScript/worker.ts
This unblocks TypeScript in VizHub.
TS support in VizHub itself has been a long standing issue. I realized that all the pieces are right here in plain sight! As we already are importing the gargantuan `ts` package in this worker, we might as well leverage it for transpilation as well!
=> Support TypeScript transpilation in Worker

src/server/computeInitialDocument.js, src/server/config.js, src/server/featureFlags.js, src/server/index.js, src/server/setupEnv.js, test/listFiles.test.js
This is a follow-up to #414.
The associated issue #110 has already been closed, let me know if it's okay to reopen that one or a new one should be created. 
I fixed some corner cases and made the implementation a little faster, plus I added the option to configure which files are used as ignore files (by default files whose name is .gitignore, .ignore or .vzignore) and what ignore patterns are included by default.
I think these are useful improvements to the previous changes, but I'm open fors suggestions if you would prefer to revert some of these additions and only keep some. 
Directory patterns with a trailing slash (e.g., `.git/` or `node_modules/`) would correctly ignore the directory's contents, but not the directory itself. 
This would result in an empty directory in the file tree. …
=> make ignore file patterns configurable with environment variables

src/types.ts
I came across a situation where content needs to be `{}`. Modified types to support this.
Also removed broken import.
=> Iterate types

src/client/VZResizer/index.tsx
In the VizHub setup, it's possible to close the sidebar. This PR just exposes an option for that, to correct the position of the right side resizer when the sidebar is closed.
=> Fix resizer bug

src/client/App/index.tsx, src/client/VZCodeContext.tsx
Moved the URL param handling into VZCodeContext, so that this feature is automatically added in downstream code that instantiates this context.
=> Refactor tab URL params to live inside VZCodeContext

src/client/CodeEditor/style.scss
=> Wrap long lines in CodeMirror tooltips

src/client/VZSidebar/index.tsx
Check this out @Akshithpottigari - it just temporarily disables the new UI until we are ready to show it.
Related to #456
=> feature flag enableConnectionStatus

src/client/App/index.tsx, src/client/App/style.scss, src/client/App/useShareDB.ts, src/client/CodeEditor/style.scss, src/client/Fonts/fonts.ts, src/client/VZCodeContext.tsx, src/client/VZSettings.tsx, src/client/VZSidebar/index.tsx
Using CSS variables for font family and the font size was easy to handle globally, and they were already present in the root, so no need to declare new variables and handle them differently, and also became handy for us to handle them throughout the app. We can add more fonts and more font sizes simply by loading them in the fonts.ts and font sizes array and we are good to go.
I have implemented #410 too, for detecting the connection status too. 
We can close #514 and #410
Thanks in advance : )
=> Closes #514

src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/index.tsx, src/client/VZCodeContext.tsx, src/client/VZMiddle.tsx
This change is to support a read-only view, used in VizHub for the "view previous version" of revision history feature.
Related to #471
=> Support read-only view when no ShareDB doc

src/client/VZCodeContext.tsx, src/client/VZSidebar/useDragAndDrop.tsx
This is a draft pull request. 
I implemented the base of the directionary process. So far:
Case 1: Regular files being dropped still works. 
Case 2: Folders when dropped seems to cause a npm error in the server/index.js file. Visually it shows up in the VZ editor however it will lose connection.
=> draganddrop for dir

package.json, src/server/index.js
I added a new environment variable for the editor port to be 5173. The index.js file then checks the editor port variable and defaults to the current port if one is not specified.
=> fixed the wrong port opening in development mode

src/client/VZCodeContext.tsx, src/client/useKeyboardShortcuts.ts
This implementation will allow users to use CTRL + Click when targetting an identifier within the current code editor to jump to its definition for various identifier types, such as variables, methods, and properties.
=> Jump to definition

src/client/CodeEditor/json1PresenceDisplay.ts
Temporarily disabling this feature for now, just because I fear it may lead to a bad experience for folks using VizHub for live events like meetups or courses, where the students all appear in the editor but are just "watching" and there is no need to follow them.
Although, I do want to make this feature available soon for users, so let's prioritize adding the UI for toggling this.
=> Temporarily disable auto-follow

src/client/useTypeScript/worker/constants.ts
Fix #770
Inspired by https://github.com/val-town/codemirror-ts?tab=readme-ov-file#setup-main-thread
The `esnext` is what apparently was missing some definitions. Changing it to es2022 and setting the target seems to have fixed it.
=> TypeScript Language Server Breakages

package.json
This change is intended to fix a bug where the local host was not running properly on some Windows machines due to an environment variable issue.
=> Changed development variable for Windows

src/client/VZSidebar/Search.tsx
The following is a small change that ensures that whenever the search view is mounted, the search input will auto-focus, improving user experience.
=> Search: Auto-focus the input field

src/client/VZKeyboardShortcutsDoc.tsx, src/client/VZSidebar/index.tsx, src/client/useKeyboardShortcuts.ts
The following adds a keyboard shortcut to trigger any sidebar buttons in the form `Ctrl + Shift + <key>`, where the shortcut model has been appended to contain information on these triggers.
=> Keyboard Shortcuts for Sidebar

src/client/VZKeyboardShortcutsDoc.tsx, src/client/VZSidebar/index.tsx, src/client/useKeyboardShortcuts.ts
The following updates each sidebar button tooltip to display their respective keyboard shortcut. An additional shortcut (`Ctrl +,`) to trigger the settings view was also added, which is based on the VS Code implementation. This fixes [#789](https://github.com/vizhub-core/vzcode/issues/789) and potentially removes the need for [#790](https://github.com/vizhub-core/vzcode/issues/790) due to the complexity of total shortcuts to represent.
=> Update Sidebar Button Tooltips

src/client/AIAssist/AIAssistCodeMirrorKeyMap.ts, src/client/AIAssist/startAIAssist.ts, src/client/CodeEditor/getOrCreateEditor.ts, src/client/CodeEditor/json1PresenceDisplay.ts, src/client/TabList/Tab.tsx, src/client/TabList/index.tsx, src/client/VZCodeContext.tsx, src/client/tabsSearchParameters.ts, src/client/useActions.ts, src/client/useURLSync.ts, src/client/vzReducer/closeTabReducer.test.ts, src/client/vzReducer/closeTabsReducer.ts, src/client/vzReducer/createInitialState.ts, src/client/vzReducer/findPane.ts, src/client/vzReducer/index.ts, src/client/vzReducer/openTabReducer.test.ts, src/client/vzReducer/openTabReducer.ts, src/client/vzReducer/setActiveFileIdReducer.ts, src/client/vzReducer/setActiveFileLeftRightReducer.ts, src/client/vzReducer/updatePane.ts, src/types.ts
This set of changes is a fairly large refactoring to introduce a recursive data structure representing split panes. 
This is the foundation upon which we can build out the split pane functionality described in #705 .
The main change is introduction of these types:
```ts
// PaneId
//   * A unique ID for a pane.
//   * This is a random string.
export type PaneId = string;
// The leaf node of the tree data structure
export type LeafPane = {
type: 'leafPane';
// The list of tabs
// Mutually exclusive with `children`.
tabList: Array<TabState>;
// The ID of the file that is currently active
// within this leaf pane.
// Invariant: `activeFileId` is always in `tabList`.
activeFileId: FileId | null;
};
// Internal node of the tree data structure
export type SplitPane = {
type: 'splitPane';
// …
```
=> Change state shape in preparation for split pane views

src/client/AIAssist/AIAssistWidget/index.tsx, src/client/CodeEditor/getOrCreateEditor.ts, src/client/VZCodeContext.tsx, src/client/useEditorCache.ts
It turns out the split pane changes broke some things because other parts of the code try to look up values from the editor cache using the old key scheme.
=> Start on fixing editor cache key mismatches

src/client/VZSidebar/styles.scss
Issue of user presence icon being behind the file icon is fixed. Brought the presence icon forwards by setting z-index to 1.
=> Added z-index in presence-indicator

src/client/VZSidebar/Search.tsx
Pressing enter on a search result leads to the same outcome.
=> Clicking on search result leads to VZCode opening the file and scrolling to the relevant text
